### ISSUE TITLE
Archive data with ZIP in envelope

### ISSUE THREAD

**Issue by Zelenyy** [mipt-npm/dataforge-core#27]

**Comment by altavir** [comment]
It will be added in next version at least for JVM. The zip will be enabled via special compression tag in `@envelop` meta block. I am not sure how it will work. There are two variants:

* Embed it into envelope format so `data` automatically uses compression algorithm on read and write without bothering user.

* Add `compress/decompress` extensions to the Envelope and an inline class that wraps data with compressor/decompressor.

**Comment by Zelenyy** [comment]
I think, we should make two variant: short and long:

Short --- boolean flags which turn on/off default zip compression
Long --- add interface for Filters (such as Photo Filters), For example:
```kotlin
interface Filters{
    fun pack(envelope : Envelope) : Envelope
    fun unpack(envelope: Envelope) : Envelope
}

class ZipFilters(val complvl : Int = 0, val algorithm : ZipAlgorithm = ZipAlgorithm.lzip) : Filters


val envelope = Envelope {
    filters : List<Filters> = listOf(ZipFilters)
    ...
}

```

**Comment by Zelenyy** [comment]
Also we can add filter which, pack double data to float for storage, and unpack in double for computation

**Comment by altavir** [comment]
> Also we can add filter which, pack double data to float for storage, and unpack in double for computation

I do not like the Idea, because this functionality is too advanced and to specific to be included in the core. Basically, it is just an implementation of serializer. It should be done inside specific modules.

**Comment by altavir** [comment]
Experimental support added via https://github.com/mipt-npm/dataforge-core/blob/6450696157998ad65922b9c164dac4a9f9915567/dataforge-workspace/src/jvmMain/kotlin/hep/dataforge/workspace/fileData.kt#L188

Test is here: https://github.com/mipt-npm/dataforge-core/blob/6450696157998ad65922b9c164dac4a9f9915567/dataforge-workspace/src/jvmTest/kotlin/hep/dataforge/workspace/FileDataTest.kt#L65
